"""
╔══════════════════════════════════════════════════════════════════════╗
║    AGENT.PY — PHASE 5 PATCH INSTRUCTIONS                            ║
║    Two changes needed — copy-paste into your agent.py               ║
╚══════════════════════════════════════════════════════════════════════╝

CHANGE 1: Add "skills_free_evolved" to SKILL_PACKS list
──────────────────────────────────────────────────────
Find this in agent.py:

    SKILL_PACKS = [
        "skills_ai",
        "skills_free_crypto",
        "skills_free_science",
        "skills_free_entertainment",
        "skills_free_knowledge",
        "skills_free_business",
        "skills_free_sentiment",
    ]

Replace with:

    SKILL_PACKS = [
        "skills_ai",
        "skills_free_crypto",
        "skills_free_science",
        "skills_free_entertainment",
        "skills_free_knowledge",
        "skills_free_business",
        "skills_free_sentiment",
        "skills_free_evolved",      # Phase 5 — auto-generated by skill_engine.py
    ]


CHANGE 2: Add reload.flag watcher + load_skill_packs() function
────────────────────────────────────────────────────────────────
Find this in agent.py (near the bottom, just BEFORE app.run()):

    if __name__ == "__main__":

Add this entire block BEFORE that line:

    # ── PHASE 5: HOT-RELOAD SKILL PACKS ──────────────────────────────
    # skill_engine.py writes reload.flag when it deploys a new skill.
    # This thread detects it and reloads all skill packs without restart.

    def load_skill_packs():
        global SKILLS, FREE_SKILLS, PAID_SKILLS
        global AI_SKILLS, AI_PAID_SKILLS
        AI_SKILLS      = {}
        AI_PAID_SKILLS = {}
        for pack_name in SKILL_PACKS:
            try:
                import importlib
                if pack_name in sys.modules:
                    mod = importlib.reload(sys.modules[pack_name])
                else:
                    mod = importlib.import_module(pack_name)
                if hasattr(mod, "SKILLS_PACK"):
                    AI_SKILLS.update(mod.SKILLS_PACK)
                elif hasattr(mod, "AI_SKILLS"):
                    AI_SKILLS.update(mod.AI_SKILLS)
                if hasattr(mod, "PAID_SKILLS_PACK"):
                    AI_PAID_SKILLS.update(mod.PAID_SKILLS_PACK)
                elif hasattr(mod, "AI_PAID_SKILLS"):
                    AI_PAID_SKILLS.update(mod.AI_PAID_SKILLS)
            except ModuleNotFoundError:
                pass
            except Exception as e:
                print(f"  [RELOAD WARN] {pack_name}: {e}")
        # Rebuild registry
        SKILLS = {
            "greet":             handle_greet,
            "random":            handle_random,
            "joke":              handle_joke,
            "wisdom":            handle_wisdom,
            "flip":              handle_flip,
            "time":              handle_time,
            "echo":              handle_echo,
            "weather":           handle_weather,
            "crypto":            handle_crypto,
            "learn_from_agents": handle_learn_from_agents,
            "share_knowledge":   handle_share_knowledge,
            "social_analysis":   handle_social_analysis,
            "personal_memory":   handle_personal_memory,
            "agent_status":      handle_agent_status,
            **AI_SKILLS,
        }
        PAID_SKILLS = {**AI_PAID_SKILLS}
        FREE_SKILLS = [s for s in SKILLS if s not in PAID_SKILLS]
        print(f"  [RELOAD] Skills reloaded: {len(SKILLS)} total")

    def watch_reload_flag():
        last_mtime = 0
        reload_flag_path = os.path.join(BASE_DIR, "reload.flag")
        while True:
            try:
                mtime = os.path.getmtime(reload_flag_path)
                if mtime > last_mtime:
                    last_mtime = mtime
                    print("[RELOAD] reload.flag changed — reloading skill packs...")
                    _time.sleep(1)  # brief wait for file write to complete
                    load_skill_packs()
                    print(f"[RELOAD] Done — {len(SKILLS)} skills now loaded")
            except FileNotFoundError:
                pass
            except Exception as e:
                print(f"[RELOAD] Error: {e}")
            _time.sleep(10)

    import threading as _threading
    _threading.Thread(target=watch_reload_flag, daemon=True).start()
    # ── END PHASE 5 PATCH ─────────────────────────────────────────────


THAT'S IT — just 2 changes. Save agent.py and restart Window 1.
"""

# ─────────────────────────────────────────────────────────────────────
# ALSO: skills_free_evolved.py starter file
# Place this on your Desktop so agent.py can import it immediately.
# skill_engine.py will expand it over time.
# ─────────────────────────────────────────────────────────────────────

EVOLVED_STARTER = '''"""
skills_free_evolved.py — Auto-generated skills by skill_engine.py
WARNING: This file is managed by skill_engine.py — do not edit manually.
New skills are added automatically every 6 hours.
"""
import requests
import datetime
import re
import json
import math
import random


# ─────────────────────────────────────────────────────────────────────
# SKILL_META: {"name": "gas_tracker", "description": "Real-time Ethereum gas prices", "created_at": "2026-05-16 00:00:00", "calls": 0, "auto": true}
# Auto-generated starter skill
# ─────────────────────────────────────────────────────────────────────

def handle_gas_tracker(params):
    """Real-time Ethereum gas prices: slow, standard, fast in Gwei."""
    data = {}
    try:
        r = requests.get("https://mempool.space/api/v1/fees/recommended", timeout=6).json()
        data["slow"]     = r.get("economyFee", "?")
        data["standard"] = r.get("halfHourFee", "?")
        data["fast"]     = r.get("fastestFee", "?")
    except Exception as e:
        return {"result": f"Gas tracker unavailable: {e}", "data": {}}

    return {
        "result": (
            f"⛽ [GAS TRACKER] Ethereum Gas Prices\\n"
            f"🐢 Slow     : {data['slow']} Gwei\\n"
            f"⚡ Standard : {data['standard']} Gwei\\n"
            f"🚀 Fast     : {data['fast']} Gwei\\n"
            f"Source: Mempool.space"
        ),
        "data": data
    }


# ─────────────────────────────────────────────────────────────────────
# SKILL_META: {"name": "fear_greed_history", "description": "Fear and Greed Index for the last 7 days", "created_at": "2026-05-16 00:00:00", "calls": 0, "auto": true}
# Auto-generated starter skill
# ─────────────────────────────────────────────────────────────────────

def handle_fear_greed_history(params):
    """Fear and Greed Index for the last 7 days showing trend."""
    try:
        r = requests.get("https://api.alternative.me/fng/?limit=7", timeout=6).json()
        entries = r.get("data", [])
        if not entries:
            return {"result": "No data available", "data": {}}

        labels = {
            "Extreme Fear": "🔴", "Fear": "🟠", "Neutral": "⚪",
            "Greed": "🟢", "Extreme Greed": "🟢🟢"
        }
        lines = ["😱 [FEAR & GREED — 7 DAY HISTORY]"]
        for e in entries:
            val   = e.get("value", "?")
            cls   = e.get("value_classification", "?")
            ts    = e.get("timestamp", "")
            emoji = labels.get(cls, "⚪")
            try:
                date = datetime.datetime.fromtimestamp(int(ts)).strftime("%b %d")
            except:
                date = "?"
            lines.append(f"  {emoji} {date}: {val}/100 — {cls}")

        trend = "improving 📈" if int(entries[0].get("value","50")) > int(entries[-1].get("value","50")) else "declining 📉"
        lines.append(f"\\n📊 7d Trend: {trend}")

        return {"result": "\\n".join(lines), "data": {"entries": entries}}
    except Exception as e:
        return {"result": f"Fear/Greed history unavailable: {e}", "data": {}}


# ─────────────────────────────────────────────────────────────────────
# SKILL_META: {"name": "btc_halving", "description": "Bitcoin halving countdown", "created_at": "2026-05-16 00:00:00", "calls": 0, "auto": true}
# Auto-generated starter skill
# ─────────────────────────────────────────────────────────────────────

def handle_btc_halving(params):
    """Bitcoin halving countdown: blocks remaining, estimated date, current epoch."""
    HALVING_INTERVAL  = 210_000
    GENESIS_HALVING   = 0
    AVG_BLOCK_MINUTES = 10

    try:
        height = requests.get("https://mempool.space/api/v1/blocks/tip/height", timeout=6).json()
        epoch  = height // HALVING_INTERVAL + 1
        next_halving_block = epoch * HALVING_INTERVAL
        blocks_remaining   = next_halving_block - height
        minutes_remaining  = blocks_remaining * AVG_BLOCK_MINUTES
        days_remaining     = minutes_remaining / (60 * 24)
        eta = datetime.datetime.now() + datetime.timedelta(days=days_remaining)

        # Current block reward
        reward = 50 / (2 ** (epoch - 1))

        return {
            "result": (
                f"₿ [BTC HALVING COUNTDOWN]\\n"
                f"📦 Current Block  : #{height:,}\\n"
                f"🎯 Next Halving   : #{next_halving_block:,}\\n"
                f"⏳ Blocks Left    : {blocks_remaining:,}\\n"
                f"📅 ETA            : ~{eta.strftime('%B %Y')} ({days_remaining:.0f} days)\\n"
                f"💰 Current Reward : {reward} BTC/block\\n"
                f"🔢 Epoch          : {epoch} (halving #{epoch-1} passed)"
            ),
            "data": {
                "height": height,
                "blocks_remaining": blocks_remaining,
                "days_remaining": round(days_remaining, 1),
                "eta": eta.strftime("%Y-%m-%d"),
                "reward_btc": reward,
                "epoch": epoch
            }
        }
    except Exception as e:
        return {"result": f"BTC halving data unavailable: {e}", "data": {}}


# ─────────────────────────────────────────────────────────────────────
# SKILL_META: {"name": "github_trending", "description": "Trending GitHub repos by stars", "created_at": "2026-05-16 00:00:00", "calls": 0, "auto": true}
# Auto-generated starter skill
# ─────────────────────────────────────────────────────────────────────

def handle_github_trending(params):
    """Trending GitHub repositories created in the last 7 days sorted by stars."""
    language = params.get("language", "")
    limit    = min(int(params.get("limit", 5)), 8)

    since = (datetime.datetime.now() - datetime.timedelta(days=7)).strftime("%Y-%m-%d")
    query = f"created:>{since}"
    if language:
        query += f" language:{language}"

    try:
        r = requests.get(
            "https://api.github.com/search/repositories",
            params={"q": query, "sort": "stars", "order": "desc", "per_page": limit},
            headers={"Accept": "application/vnd.github.v3+json"},
            timeout=8
        ).json()

        repos = r.get("items", [])
        if not repos:
            return {"result": "No trending repos found this week.", "data": {}}

        lang_str = f" ({language})" if language else ""
        lines = [f"⭐ [GITHUB TRENDING{lang_str} — Last 7 Days]"]
        for repo in repos:
            stars = repo.get("stargazers_count", 0)
            name  = repo.get("full_name", "?")
            desc  = str(repo.get("description", ""))[:60]
            lang  = repo.get("language") or "?"
            lines.append(f"• ⭐{stars:,} | {name} ({lang})\\n  {desc}")

        return {
            "result": "\\n".join(lines),
            "data": {"repos": [{"name": r.get("full_name"), "stars": r.get("stargazers_count")} for r in repos]}
        }
    except Exception as e:
        return {"result": f"GitHub trending unavailable: {e}", "data": {}}


# ─────────────────────────────────────────────────────────────────────
# SKILL_META: {"name": "defi_tvl_rank", "description": "Top DeFi protocols by TVL", "created_at": "2026-05-16 00:00:00", "calls": 0, "auto": true}
# Auto-generated starter skill
# ─────────────────────────────────────────────────────────────────────

def handle_defi_tvl_rank(params):
    """Top DeFi protocols by Total Value Locked from DeFiLlama."""
    limit = min(int(params.get("limit", 8)), 15)
    try:
        r = requests.get("https://api.llama.fi/protocols", timeout=8).json()
        top = sorted(r, key=lambda x: x.get("tvl", 0), reverse=True)[:limit]

        lines = [f"🏆 [TOP {limit} DEFI PROTOCOLS BY TVL]"]
        for i, p in enumerate(top, 1):
            tvl   = p.get("tvl", 0)
            name  = p.get("name", "?")
            chain = p.get("chain", "Multi")
            cat   = p.get("category", "?")
            lines.append(f"{i:2}. {name:20} | ${tvl:>14,.0f} | {chain} | {cat}")

        return {
            "result": "\\n".join(lines),
            "data": {"protocols": [{"name": p.get("name"), "tvl": p.get("tvl")} for p in top]}
        }
    except Exception as e:
        return {"result": f"DeFi TVL unavailable: {e}", "data": {}}


SKILLS_PACK = {
    "gas_tracker":         handle_gas_tracker,
    "fear_greed_history":  handle_fear_greed_history,
    "btc_halving":         handle_btc_halving,
    "github_trending":     handle_github_trending,
    "defi_tvl_rank":       handle_defi_tvl_rank,
}
'''

if __name__ == "__main__":
    import os

    # Write the starter skills_free_evolved.py
    desktop = os.path.join(os.path.expanduser("~"), "OneDrive", "Desktop")
    out_path = os.path.join(desktop, "skills_free_evolved.py")

    with open(out_path, "w", encoding="utf-8") as f:
        f.write(EVOLVED_STARTER)

    print(f"✅ skills_free_evolved.py written to: {out_path}")
    print("   Now follow the agent.py patch instructions at the top of this file.")
    print("   Then restart Window 1 (agent.py) and run skill_engine.py in Window 4.")
