"""
skills_free_evolved.py — Auto-generated skills by skill_engine.py
WARNING: This file is managed by skill_engine.py — do not edit manually.
New skills are added automatically every 6 hours.
"""
import requests
import datetime
import re
import json
import math
import random







# ─────────────────────────────────────────────────────────────────────
# SKILL_META: {"name": "stablecoin_watch", "description": "Top stablecoins by market cap and peg status from CoinGecko.", "created_at": "2026-05-21 18:33:43", "calls": 0, "auto": true}
# Auto-generated by skill_engine.py at 2026-05-21 18:33:43
# ─────────────────────────────────────────────────────────────────────

def handle_stablecoin_watch(params):
    try:
        api_url = "https://api.coingecko.com/api/v3/coins/markets"
        params = {
            "vs_currency": "usd",
            "order": "market_cap_desc",
            "per_page": 10,
            "page": 1,
            "sparkline": False
        }
        response = requests.get(api_url, params=params)
        response.raise_for_status()
        data = response.json()
        stablecoins = [coin for coin in data if coin['name'].lower().endswith(('usd', 'eur', 'gbp', 'chf'))]
        result = f"📈 Top Stablecoins by Market Cap:\n"
        for i, coin in enumerate(stablecoins):
            result += f"{i+1}. {coin['name']} - {coin['market_cap']} USD\n"
        return {"result": result, "data": stablecoins}
    except requests.RequestException as e:
        return {"result": f"API request failed: {e}", "data": []}

# ─────────────────────────────────────────────────────────────────────
# SKILL_META: {"name": "country_facts", "description": "Quick country facts: population, capital, GDP, flag emoji. Source: restcountries.com.", "created_at": "2026-05-28 08:52:55", "calls": 0, "auto": true}
# Auto-generated by skill_engine.py at 2026-05-28 08:52:55
# ─────────────────────────────────────────────────────────────────────

def handle_country_facts(params):
    country = params.get("country", "").strip()
    if not country:
        return {"result": "Please provide a country name.", "data": {}}

    try:
        import requests
        import datetime
        import re
        import random
        import math

        url = f"https://restcountries.com/v3.1/name/{country}"
        response = requests.get(url, timeout=10)
        response.raise_for_status()
        data = response.json()

        if not data or "status" in data:
            return {"result": "Country not found. Please check the spelling.", "data": {}}

        country_data = data[0]
        name = country_data.get("name", {}).get("common", "Unknown")
        capital = ", ".join(country_data.get("capital", ["Unknown"]))
        population = country_data.get("population", "Unknown")
        gdp = "Unknown"
        currencies = country_data.get("currencies", {})
        if currencies:
            currency_code = next(iter(currencies))
            gdp = country_data.get("gdp", {}).get(currency_code, "Unknown")
        flag = country_data.get("flag", "❓")

        result = (
            f"🇪🇺 {name}\n"
            f"🏛️ Capital: {capital}\n"
            f"👥 Population: {population:,}\n"
            f"💰 GDP: {gdp}\n"
            f"🏳️ Flag: {flag}"
        )

        return {
            "result": result,
            "data": {
                "name": name,
                "capital": capital,
                "population": population,
                "gdp": gdp,
                "flag": flag,
                "source": url
            }
        }

    except Exception as e:
        fallback = {
            "result": f"Could not fetch data for '{country}'. Please try again later.",
            "data": {"error": str(e)}
        }
        return fallback

# ─────────────────────────────────────────────────────────────────────
# SKILL_META: {"name": "isp_lookup", "description": "Look up ISP, city, country and timezone for any IP address. Source: ip-api.com.", "created_at": "2026-05-28 20:55:13", "calls": 0, "auto": true}
# Auto-generated by skill_engine.py at 2026-05-28 20:55:13
# ─────────────────────────────────────────────────────────────────────

def handle_isp_lookup(params):
    ip = params.get("ip", "8.8.8.8")
    result = {"result": "⚠️ ISP lookup failed", "data": {}}
    url = f"http://ip-api.com/json/{ip}"
    try:
        response = requests.get(url, timeout=5)
        data = response.json()
        if data.get("status") == "success":
            isp = data.get("isp", "Unknown ISP")
            org = data.get("org", "Unknown Organization")
            as_info = data.get("as", "Unknown AS")
            city = data.get("city", "Unknown City")
            country = data.get("country", "Unknown Country")
            timezone = data.get("timezone", "Unknown Timezone")
            lat = data.get("lat", 0)
            lon = data.get("lon", 0)
            result["result"] = f"🌐 ISP Lookup for {ip}\n📡 ISP: {isp}\n🏢 Org: {org}\n🔗 AS: {as_info}\n🏙️ City: {city}\n🌍 Country: {country}\n🕒 Timezone: {timezone}\n📍 Coordinates: ({lat}, {lon})"
            result["data"] = {
                "ip": ip,
                "isp": isp,
                "organization": org,
                "as": as_info,
                "city": city,
                "country": country,
                "timezone": timezone,
                "latitude": lat,
                "longitude": lon
            }
    except Exception as e:
        result["result"] = f"⚠️ ISP lookup failed: {str(e)}"
    return result

# ─────────────────────────────────────────────────────────────────────
# SKILL_META: {"name": "wikipedia_summary", "description": "Get a Wikipedia summary for any topic in 3-5 sentences.", "created_at": "2026-05-29 18:24:34", "calls": 0, "auto": true}
# Auto-generated by skill_engine.py at 2026-05-29 18:24:34
# ─────────────────────────────────────────────────────────────────────

def handle_wikipedia_summary(params):
    topic = params.get("topic", "").strip()
    if not topic:
        return {"result": "❌ Please provide a valid topic.", "data": {}}

    url = f"https://en.wikipedia.org/api/rest_v1/page/summary/{topic}"
    result = {"result": "⚠️ Failed to fetch Wikipedia summary.", "data": {}}

    try:
        import requests
        response = requests.get(url, timeout=10)
        response.raise_for_status()
        data = response.json()

        if "extract" in data and "title" in data:
            summary = data["extract"]
            sentences = [s.strip() for s in summary.split(". ") if s.strip()]
            formatted_summary = ". ".join(sentences[:3]) + "."
            result["result"] = f"📖 **{data['title']}**\n{formatted_summary}"
            result["data"] = {
                "title": data["title"],
                "extract": data["extract"],
                "url": data.get("content_urls", {}).get("desktop", {}).get("page", "")
            }
        else:
            result["result"] = "❌ No summary found for the given topic."
    except Exception as e:
        result["result"] = f"⚠️ Wikipedia API error: {str(e)}"

    return result

# ─────────────────────────────────────────────────────────────────────
# SKILL_META: {"name": "air_quality", "description": "Air quality index and PM2.5 for any city. Source: open-meteo air quality API.", "created_at": "2026-06-02 04:23:10", "calls": 0, "auto": true}
# Auto-generated by skill_engine.py at 2026-06-02 04:23:10
# ─────────────────────────────────────────────────────────────────────

def handle_air_quality(params):
    city = params.get("city", "London")
    api_url = "https://air-quality-api.open-meteo.com/v1/air-quality"

    try:
        response = requests.get(api_url, params={"location": city})
        response.raise_for_status()
        data = response.json()

        if "results" not in data or not data["results"]:
            return {
                "result": f"⚠️ No air quality data found for {city}",
                "data": {"city": city, "error": "No results in API response"}
            }

        result = data["results"][0]
        pm25 = result.get("pm2_5", "N/A")
        aqi = result.get("aqi", "N/A")

        if pm25 == "N/A" or aqi == "N/A":
            return {
                "result": f"⚠️ Incomplete air quality data for {city}",
                "data": {"city": city, "pm2_5": pm25, "aqi": aqi}
            }

        aqi_level = (
            "Good" if aqi <= 50 else
            "Moderate" if aqi <= 100 else
            "Unhealthy for Sensitive Groups" if aqi <= 150 else
            "Unhealthy" if aqi <= 200 else
            "Very Unhealthy" if aqi <= 300 else
            "Hazardous"
        )

        result_str = (
            f"🌍 Air Quality in {city}\n"
            f"📊 AQI: {aqi} ({aqi_level})\n"
            f"💨 PM2.5: {pm25} µg/m³"
        )

        return {
            "result": result_str,
            "data": {
                "city": city,
                "aqi": aqi,
                "aqi_level": aqi_level,
                "pm2_5": pm25,
                "timestamp": datetime.datetime.now().isoformat()
            }
        }

    except requests.exceptions.RequestException as e:
        return {
            "result": f"⚠️ Could not fetch air quality data for {city}. API error: {str(e)}",
            "data": {"city": city, "error": str(e)}
        }
    except Exception as e:
        return {
            "result": f"⚠️ Unexpected error fetching air quality data for {city}.",
            "data": {"city": city, "error": str(e)}
        }



SKILLS_PACK = {
    "stablecoin_watch": handle_stablecoin_watch,
    "country_facts": handle_country_facts,
    "isp_lookup": handle_isp_lookup,
    "wikipedia_summary": handle_wikipedia_summary,
    "air_quality": handle_air_quality,
}
